[package]
name = "answer"
version = "0.0.1-beta.1"
edition = "2021"
authors = ["Felipe S. S. Schneider <schneider.felipe.5@gmail.com>"]
description = "answer any question right from your terminal, using the same large language model that powers ChatGPT"
homepage = "https://github.com/schneiderfelipe/getanswe.rs/tree/main/answer"
repository = "https://github.com/schneiderfelipe/getanswe.rs"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71" }
async-openai = { version = "0.28.0" }
clap = { version = "4.2.7" }
clap-verbosity-flag = { version = "3.0.0" }
futures = { version = "0.3.28" }
human-panic = { version = "2.0.0" }
log = { version = "0.4.17" }
pretty_env_logger = { version = "0.5.0" }
serde = { version = "1.0.163" }
serde_yaml = { version = "0.9.21" }
thiserror = { version = "2.0.3" }
tokio = { version = "1.28.1", features = ["io-std", "rt-multi-thread"] }
