name: Changelog

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-readme
          version: latest
          use-tool-cache: true
      - name: Update answer/README.md
        working-directory: ./answer
        run: cargo readme > README.md
      - name: Update murmur/README.md
        working-directory: ./murmur
        run: cargo readme > README.md
      - name: Update reply/README.md
        working-directory: ./reply
        run: cargo readme > README.md

      - uses: orhun/git-cliff-action@v4
        env:
          OUTPUT: CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(changelog): update"
